server:
  port: 3344

spring:
  application:
    name: cloud-config-center  #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RamboNumber/springcloud-config.git  #github上面的仓库路径
          ## 搜索目录
          search-paths:
            - springcloud-config
      ## 读取分支
      label: master


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka