server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    # 表示不向注册中心注册自己
    register-with-eureka: false
    # 表示自己段就是注册中心， 我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    #设置与eureka Server交互的地址查询服务和注册服务都需要以来这个地址（可视化页面）
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka

#  server:
    #关闭自我保护机制，保证不可用服务即使清除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000