server:
  port: 8001

spring:
  application:
    name: cloud-provider-hsytrix-payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

  instance:
    instance-id: cloud-provider-hsytrix-payment8001
    prefer-ip-address: true